name: Magnesium
version: 0.0.1
description: A open source core plugin
main: com.jackthewebdev.Magnesium.Magnesium
commands:
  test:
    description: Test everything
  report:
    description: Report a uesr
  mg reload:
    description: Reload the configuration files
  profile:
    description: View a users profile